//! sigtool - signatures of the engine addresses MPFever's native module hooks.
//!
//!   sigtool make  <TransportFever3.exe> <known_<build>.txt> <out signatures.txt> [--header <signatures_gen.h>]
//!       builds a unique signature for every known address of that build (the exe must be that build)
//!   sigtool check <TransportFever3.exe> <signatures.txt> [--known <known_<build>.txt>] [--json]
//!       resolves every signature in an exe (any build): each must match exactly once; with --known the results
//!       must equal the known addresses. Exit code 0 only when everything resolved (and matched).
//!
//! The native module (native/mpfever_native.cpp) includes the generated header and resolves the same signatures at
//! run time when it does not know the game build (Phase 2).

use mpf_pe::Pe;
use mpf_sig::{byte_freq, make, Signature};
use std::fmt::Write as _;
use std::path::Path;
use std::process::ExitCode;

struct Known {
    stamp: u32,
    entries: Vec<(String, u32, bool)>,
}

fn parse_hex(s: &str) -> Option<u32> {
    u32::from_str_radix(s.trim().trim_start_matches("0x"), 16).ok()
}

fn read_known(path: &Path) -> Result<Known, String> {
    let text = std::fs::read_to_string(path).map_err(|e| format!("{}: {e}", path.display()))?;
    let mut k = Known { stamp: 0, entries: vec![] };
    for line in text.lines() {
        let line = line.trim_end();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let f: Vec<&str> = line.split('\t').collect();
        if f[0] == "stamp" && f.len() >= 2 {
            k.stamp = parse_hex(f[1]).ok_or(format!("bad stamp: {line}"))?;
        } else if f.len() >= 3 {
            k.entries.push((f[0].to_string(), parse_hex(f[1]).ok_or(format!("bad rva: {line}"))?, f[2] == "entry"));
        } else {
            return Err(format!("bad line: {line}"));
        }
    }
    Ok(k)
}

fn read_sigs(path: &Path) -> Result<Vec<Signature>, String> {
    let text = std::fs::read_to_string(path).map_err(|e| format!("{}: {e}", path.display()))?;
    text.lines()
        .filter(|l| !l.trim().is_empty() && !l.starts_with('#'))
        .map(|l| Signature::parse_line(l).map_err(|e| e.to_string()))
        .collect()
}

fn header(sigs: &[Signature], build: u32) -> String {
    let mut h = String::new();
    let _ = writeln!(h, "// Generated by tools/sigtool from signatures/signatures.txt (made on build stamp {build:#x}). Do not edit.");
    let _ = writeln!(h, "// The native module resolves these when it does not know the game build (Phase 2).");
    let _ = writeln!(h, "#pragma once");
    for s in sigs {
        let bytes: Vec<String> = s.bytes.iter().map(|b| format!("0x{:02x}", b.unwrap_or(0))).collect();
        let mask: Vec<String> = s.bytes.iter().map(|b| if b.is_some() { "1".into() } else { "0".into() }).collect();
        let _ = writeln!(h, "static const u8 SIGB_{}[] = {{ {} }};", s.name, bytes.join(", "));
        let _ = writeln!(h, "static const u8 SIGM_{}[] = {{ {} }};", s.name, mask.join(", "));
    }
    let _ = writeln!(h, "struct SigDef {{ const char* name; int offset; int len; const u8* bytes; const u8* mask; }};");
    let _ = writeln!(h, "static const SigDef SIGS[] = {{");
    for s in sigs {
        let _ = writeln!(h, "    {{ \"{0}\", {1}, {2}, SIGB_{0}, SIGM_{0} }},", s.name, s.offset, s.bytes.len());
    }
    let _ = writeln!(h, "}};");
    let _ = writeln!(h, "static const int N_SIGS = (int)(sizeof(SIGS) / sizeof(SIGS[0]));");
    h
}

fn cmd_make(args: &[String]) -> Result<(), String> {
    if args.len() < 3 {
        return Err("usage: sigtool make <exe> <known.txt> <out.txt> [--header <file.h>]".into());
    }
    let pe = Pe::open(Path::new(&args[0])).map_err(|e| e.to_string())?;
    let known = read_known(Path::new(&args[1]))?;
    if pe.timestamp != known.stamp {
        return Err(format!("the exe is build stamp {:#x}, the known addresses are for {:#x}", pe.timestamp, known.stamp));
    }
    let freq = byte_freq(pe.text().ok_or("no .text")?.1);
    let mut sigs = vec![];
    for (name, rva, entry) in &known.entries {
        let s = make(&pe, name, *rva, *entry, &freq).map_err(|e| e.to_string())?;
        let back = s.resolve(&pe, &freq).map_err(|e| e.to_string())?;
        if back != *rva {
            return Err(format!("{name}: signature resolves to {back:#x}, not {rva:#x}"));
        }
        println!("{name:<12} {rva:#09x}  {} bytes, offset {}", s.bytes.len(), s.offset);
        sigs.push(s);
    }
    let mut out = format!("# Signatures of the engine addresses MPFever hooks (tools/sigtool make, build stamp {:#x}).\n", pe.timestamp);
    out.push_str("# name<TAB>offset<TAB>pattern (?? = wildcard)\n");
    for s in &sigs {
        out.push_str(&s.to_line());
        out.push('\n');
    }
    std::fs::write(&args[2], out).map_err(|e| e.to_string())?;
    if let Some(i) = args.iter().position(|a| a == "--header") {
        let path = args.get(i + 1).ok_or("--header needs a file")?;
        std::fs::write(path, header(&sigs, pe.timestamp)).map_err(|e| e.to_string())?;
    }
    Ok(())
}

fn cmd_check(args: &[String]) -> Result<bool, String> {
    if args.len() < 2 {
        return Err("usage: sigtool check <exe> <signatures.txt> [--known <known.txt>] [--json]".into());
    }
    let pe = Pe::open(Path::new(&args[0])).map_err(|e| e.to_string())?;
    let sigs = read_sigs(Path::new(&args[1]))?;
    let known = match args.iter().position(|a| a == "--known") {
        Some(i) => Some(read_known(Path::new(args.get(i + 1).ok_or("--known needs a file")?))?),
        None => None,
    };
    let json = args.iter().any(|a| a == "--json");
    let freq = byte_freq(pe.text().ok_or("no .text")?.1);
    let mut ok = true;
    let mut rows = vec![];
    for s in &sigs {
        let res = s.resolve(&pe, &freq);
        let expected = known.as_ref().and_then(|k| k.entries.iter().find(|e| e.0 == s.name).map(|e| e.1));
        let (rva, status) = match (&res, expected) {
            (Ok(r), Some(e)) if *r != e => (Some(*r), format!("MISMATCH (known {e:#x})")),
            (Ok(r), _) => (Some(*r), "ok".to_string()),
            (Err(e), _) => (None, e.to_string()),
        };
        if status != "ok" {
            ok = false;
        }
        rows.push((s.name.clone(), rva, status));
    }
    if json {
        let items: Vec<String> = rows
            .iter()
            .map(|(n, r, st)| {
                format!(
                    "{{\"name\":\"{n}\",\"rva\":{},\"status\":\"{}\"}}",
                    r.map(|v| v.to_string()).unwrap_or("null".into()),
                    st.replace('"', "'")
                )
            })
            .collect();
        println!("{{\"stamp\":{},\"ok\":{ok},\"signatures\":[{}]}}", pe.timestamp, items.join(","));
    } else {
        println!("build stamp {:#x}", pe.timestamp);
        for (n, r, st) in &rows {
            println!("{n:<12} {:<10} {st}", r.map(|v| format!("{v:#x}")).unwrap_or("-".into()));
        }
        println!("{}", if ok { "ALL RESOLVED" } else { "NOT ALL RESOLVED" });
    }
    Ok(ok)
}

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let result = match args.first().map(|s| s.as_str()) {
        Some("make") => cmd_make(&args[1..]).map(|_| true),
        Some("check") => cmd_check(&args[1..]),
        _ => Err("usage: sigtool make|check ... (see the source header)".into()),
    };
    match result {
        Ok(true) => ExitCode::SUCCESS,
        Ok(false) => ExitCode::from(1),
        Err(e) => {
            eprintln!("sigtool: {e}");
            ExitCode::from(2)
        }
    }
}
